-- AlterTable
ALTER TABLE `event` ADD COLUMN `goingCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `maybeCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `notGoingCount` INTEGER NOT NULL DEFAULT 0,
    MODIFY `attendees` INTEGER NOT NULL DEFAULT 0;
